# Generated by Codex on 2026-07-01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("authentication", "0004_auditlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="denied_permissions",
            field=models.ManyToManyField(
                blank=True,
                related_name="denied_user_set",
                to="auth.permission",
                verbose_name="denied permissions",
            ),
        ),
    ]
