# Generated by Django 5.2.10 on 2026-04-10 05:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('short_code', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.IntegerField(choices=[(1, 'Active'), (2, 'Archived')], default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReportingFrequency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('short_code', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('months_interval', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('short_code', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('target', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Active'), (2, 'Archive')], default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pme.document')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='pme.item')),
                ('unit_of_measure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.unitofmeasure')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Initiative',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=500)),
                ('target_date', models.DateField()),
                ('value', models.DecimalField(decimal_places=2, max_digits=18)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='report_submissions', to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='initiatives', to='core.unit')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='pme.item')),
            ],
        ),
        migrations.CreateModel(
            name='ItemContributor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributors', to='pme.item')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_contributions', to='core.unit')),
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='reporting_frequency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='pme.reportingfrequency'),
        ),
        migrations.CreateModel(
            name='ReportingPeriod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period_number', models.PositiveIntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('deadline', models.DateField()),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reporting_periods', to='pme.document')),
            ],
        ),
        migrations.CreateModel(
            name='InitiativeAccomplishment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_path', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('initiative', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='accomplishment', to='pme.initiative')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='initiative_accomplishments', to=settings.AUTH_USER_MODEL)),
                ('reporting_period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='pme.reportingperiod')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='document',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='pme.template'),
        ),
        migrations.CreateModel(
            name='TemplateNodeType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('short_code', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_parent', models.BooleanField(default=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='node_types', to='pme.template')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='item',
            name='template_node_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pme.templatenodetype'),
        ),
        migrations.AddIndex(
            model_name='initiative',
            index=models.Index(fields=['item', 'description'], name='pme_initiat_item_id_355a47_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='itemcontributor',
            unique_together={('item', 'unit')},
        ),
        migrations.AlterUniqueTogether(
            name='reportingperiod',
            unique_together={('document', 'period_number')},
        ),
        migrations.AddIndex(
            model_name='initiativeaccomplishment',
            index=models.Index(fields=['initiative', 'reporting_period'], name='pme_initiat_initiat_60223f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='templatenodetype',
            unique_together={('template', 'name')},
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['document'], name='pme_item_documen_56ddc1_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['parent'], name='pme_item_parent__559813_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['template_node_type'], name='pme_item_templat_adf9c6_idx'),
        ),
    ]
