# Generated by Django 5.2.10 on 2026-06-22 06:26

import apps.pme.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pme', '0002_alter_initiativeaccomplishment_file_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='initiativeaccomplishment',
            name='file_path',
            field=models.FileField(blank=True, null=True, upload_to=apps.pme.models.initiative_evidence_upload_path),
        ),
    ]
