# Generated by Django 5.2.10 on 2026-06-22 13:53

import apps.pme.models
import django.db.models.deletion
import uuid
from django.db import migrations, models
from django.utils import timezone


def copy_existing_evidence_files(apps, schema_editor):
    InitiativeAccomplishment = apps.get_model("pme", "InitiativeAccomplishment")
    InitiativeAccomplishmentFile = apps.get_model("pme", "InitiativeAccomplishmentFile")
    now = timezone.now()

    evidence_files = []
    for accomplishment in InitiativeAccomplishment.objects.exclude(file_path__isnull=True).exclude(file_path=""):
        evidence_files.append(
            InitiativeAccomplishmentFile(
                accomplishment_id=accomplishment.id,
                file_path=accomplishment.file_path,
                status=1,
                created_at=now,
                updated_at=now,
            )
        )

    if evidence_files:
        InitiativeAccomplishmentFile.objects.bulk_create(evidence_files)


class Migration(migrations.Migration):

    dependencies = [
        ('pme', '0003_alter_initiativeaccomplishment_file_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='initiativeaccomplishment',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Active'), (2, 'Reverted')], default=1),
        ),
        migrations.CreateModel(
            name='InitiativeAccomplishmentFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_path', models.FileField(upload_to=apps.pme.models.initiative_evidence_upload_path)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Active'), (2, 'Reverted')], default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accomplishment', models.ForeignKey(db_column='pia_id', on_delete=django.db.models.deletion.CASCADE, related_name='files', to='pme.initiativeaccomplishment')),
            ],
            options={
                'db_table': 'pme_initiativeaccomplishment_files',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['accomplishment', 'status'], name='pme_initiat_pia_id_888f0f_idx')],
            },
        ),
        migrations.RunPython(copy_existing_evidence_files, migrations.RunPython.noop),
    ]
